repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: debug-statements
      # - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: ^tests/fixtures/|^microservice/|tests/.*
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=120
        exclude: migrations/.*|__init__.py|^microservice/|tests/.*
  - repo: https://github.com/PyCQA/pylint
    rev: v2.16.2
    hooks:
      - id: pylint
        args:
          - --max-line-length=120
          - --disable=missing-module-docstring,missing-class-docstring,ungrouped-imports,misplaced-format-function,E0401,R0801,R0903,W0613,W0718,C0412,C0209
        exclude: migrations/.*|^microservice/|tests/.*
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        args:
          - --line-length=120
          - --skip-string-normalization
          - --exclude=homeassistant/components/plex/plexapi/.*
        exclude: migrations/.*|^microservice/|tests/.*
